# Generated by Django 3.1.4 on 2021-01-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='siape',
        ),
    ]
