# Generated by Django 3.1.4 on 2021-12-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user/', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='campus',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Campus'),
        ),
    ]
