# Generated by Django 3.1.4 on 2021-05-10 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='user/', verbose_name='Avatar'),
            preserve_default=False,
        ),
    ]
