# Generated by Django 3.1.4 on 2021-06-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='campus',
            field=models.TextField(blank=True, null=True, verbose_name='Campus'),
        ),
    ]
