# Generated by Django 3.1.4 on 2021-06-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210621_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='campus',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Campus'),
        ),
    ]
