# Generated by Django 3.1.4 on 2021-12-28 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_directorship'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='directorship',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.directorship'),
        ),
    ]
