# Generated by Django 3.1.4 on 2022-01-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.EmailField(max_length=100, verbose_name='Email')),
                ('recipient', models.CharField(max_length=100000, verbose_name='Emails dos Destinatarios')),
                ('subject', models.CharField(max_length=100, verbose_name='Assunto')),
                ('message', models.CharField(max_length=100000, verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
    ]
