# Generated by Django 3.1.4 on 2022-01-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0003_course_directorship'),
        ('board', '0006_auto_20211228_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.EmailField(max_length=100, verbose_name='Email')),
                ('recipient_year', models.CharField(max_length=300, verbose_name='Ano')),
                ('recipient_period', models.CharField(max_length=300, verbose_name='Periodo')),
                ('recipient_count', models.IntegerField(null=True)),
                ('subject', models.CharField(max_length=100, verbose_name='Assunto')),
                ('message', models.CharField(max_length=100000, verbose_name='Mensagem')),
                ('recipient_board', models.ManyToManyField(blank=True, related_name='boards', to='board.Board', verbose_name='Placa')),
                ('recipient_course', models.ManyToManyField(blank=True, related_name='courses', to='course.Course', verbose_name='Curso')),
                ('recipient_directorship', models.ManyToManyField(blank=True, related_name='directorships', to='course.Directorship', verbose_name='Diretoria')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
    ]
