# Generated by Django 3.1.4 on 2022-01-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sending',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='sending/', verbose_name='Arquivo'),
        ),
    ]
