# Generated by Django 3.1.4 on 2021-01-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egress',
            name='photo',
            field=models.ImageField(upload_to='egress/images/', verbose_name='Imagem'),
        ),
    ]
