# Generated by Django 3.1.4 on 2021-05-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egress',
            name='lattes',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Lattes'),
        ),
        migrations.AlterField(
            model_name='egress',
            name='social_network',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Rede social'),
        ),
    ]
