# Generated by Django 3.1.4 on 2021-01-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egress', '0002_auto_20210105_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egress',
            name='photo',
            field=models.ImageField(upload_to='egress/', verbose_name='Imagem'),
        ),
    ]
