# Generated by Django 3.1.4 on 2021-02-11 19:32

import board.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentioned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=300, verbose_name='Nome')),
                ('mention', models.SmallIntegerField(choices=[(0, 'Reitor'), (1, 'Paraninfo'), (2, 'Patrono'), (3, 'DG'), (4, 'DE'), (5, 'Em memoria'), (6, 'Funcionário'), (7, 'Homenageado'), (8, 'Orador')], verbose_name='Tipo de menção')),
            ],
            options={
                'verbose_name': 'Mencionado',
                'verbose_name_plural': 'Mencionados',
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=300, verbose_name='Nome')),
                ('photo', models.ImageField(upload_to='board/', verbose_name='Imagem')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mensagem')),
                ('year_graduation', models.DateField(default=board.models.current_year, verbose_name='Ano do período')),
                ('period_graduation', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)], verbose_name='Período')),
                ('graduation_date', models.DateField(verbose_name='Data da formatura')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('mentioned', models.ManyToManyField(blank=True, related_name='mentioneds', to='board.Mentioned', verbose_name='Mencionado')),
            ],
            options={
                'verbose_name': 'PLaca',
                'verbose_name_plural': 'Placas',
            },
        ),
    ]
