# Generated by Django 3.1.4 on 2021-01-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='mentioned',
            field=models.ManyToManyField(blank=True, related_name='mentioneds', to='board.Mentioned', verbose_name='Mencionado'),
        ),
    ]
