# Generated by Django 3.1.4 on 2021-04-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='year_graduation',
            field=models.IntegerField(verbose_name='Ano do período'),
        ),
    ]
