# Generated by Django 3.1.4 on 2020-12-30 00:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('board', '0002_auto_20201229_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='course',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
    ]
