# Generated by Django 3.1.4 on 2021-05-26 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('board', '0002_auto_20210427_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.campus'),
        ),
    ]
