# Generated by Django 3.1.4 on 2021-12-21 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('board', '0002_board_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.campus'),
        ),
    ]
