# Generated by Django 3.1.4 on 2021-06-22 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_campus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'Placa', 'verbose_name_plural': 'Placas'},
        ),
    ]
