# Generated by Django 3.1.4 on 2021-02-02 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_mentioned_siape'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='period_graduation',
            field=models.IntegerField(default=django.utils.timezone.now, verbose_name='Período'),
            preserve_default=False,
        ),
    ]
