# Generated by Django 3.1.4 on 2021-12-21 15:45

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20211221_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='year_graduation',
            field=models.IntegerField(default=board.models.current_year, verbose_name='Ano do período'),
        ),
    ]
