# Generated by Django 3.1.4 on 2021-12-21 15:49

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20211221_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='year_graduation',
            field=models.CharField(default=board.models.current_year, max_length=5, verbose_name='Ano do período'),
        ),
    ]
