# Generated by Django 3.1.4 on 2021-02-02 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_board_period_graduation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='period_graduation',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)], verbose_name='Período'),
        ),
    ]
