# Generated by Django 3.1.4 on 2021-12-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20211221_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem da turma'),
        ),
    ]
