name: Django Test Workflow

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Django Testing project
        env:
          SECRET_KEY: fake^6gf-kok-secret(key
          ALLOWED_HOSTS: 127.0.0.1, .localhost
          HOST: http://localhost:8000/
          WEB_CONCURRENCY: 3
          CLIENTE_ID: fakeClientId
          CLIENT_SECRET: fakeClientSecret
          TOKEN_SUAP_SECRET: fakeTokenSuapSecret
          EMAIL_HOST: smtp.sendgrid.net
          EMAIL_PORT: 2525
          EMAIL_HOST_USER: faekEmailHostUser
        run: |
          yes "yes" | python3 manage.py makemigrations
          yes "yes" | python3 manage.py migrate
          yes "yes" | python3 manage.py test
